config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resource  :session
  resources :stages

  resources :stages do
    resources :messages
    put :reset, on: :member
    get :reload, on: :member
    get :stop, on: :member
  end
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base

  # Store a band mates code
  # contribution to a stage.
  # Can be modified via sending
  # messages to the stage.

  belongs_to :user
  belongs_to :stage

end

app/models/message.rb
class Message < ActiveRecord::Base

  NOTIFICATIONS = [
    'raises their fists to the air!',
    'shakes their hair!',
    'brought in a new tune!',
  ]

  # validations
  #
  #

  validates :user, presence: true

  # associations
  #
  #

  belongs_to :stage
  belongs_to :user

  # callbacks
  #
  #

  after_commit :broadcast

  # instance methods
  #
  #

  def contribution
    Contribution.find_by(user: user, stage: stage).presence || user.contributions.create(stage: stage, content: content)
  end

  private

  def broadcast
    ActionCable.server.broadcast(
      "stages:#{self.stage_id}:messages",
      message: MessagesController.render(partial: 'messages/message', locals: { message: self })
    )
  end

end

app/models/stage.rb
class Stage < ActiveRecord::Base

  # validations
  #
  #

  validates :user, presence: true

  # associations
  #
  #

  belongs_to :user
  has_many :messages
  has_many :contributions

  # instance methods
  #
  #

  def performance
    contributions.pluck(:content).join("\n# ---\n")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  has_many :stages
  has_many :contributions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  protect_from_forgery with: :exception
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :ensure_authenticated_user
  end

  private

  def ensure_authenticated_user
    authenticate_user(cookies.signed[:user_id]) || redirect_to(new_session_url)
  end

  def authenticate_user(user_id)
    if authenticated_user = User.find_by(id: user_id)
      cookies.signed[:user_id] ||= user_id
      @current_user = authenticated_user
    end
  end

  def unauthenticate_user
    ActionCable.server.disconnect(current_user: @current_user)
    @current_user = nil
    cookies.delete(:user_id)
  end
end

app/controllers/messages_controller.rb
require 'sonic_pi'

class MessagesController < ApplicationController
  before_action :set_stage

  def create
    @message = Message.create! permitted_params
    @message.contribution.update_column :content, @message.content
    pi.run(current_stage.performance)
  end

  private

  def set_stage
    @stage = Stage.find(params[:stage_id])
  end

  def current_stage
    @stage
  end

  def current_user
    @current_user
  end

  def pi
    @pi ||= begin
              proxy = SonicPi.new
              proxy.test_connection!
              proxy
            end
  end

  def permitted_params
    params.require(:message).permit(:content).merge({ stage: current_stage, user: current_user })
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_authenticated_user, only: %i( new create )

  def new
    @users = User.all
  end

  def create
    authenticate_user(params[:user_id])
    redirect_to stages_url
  end

  def destroy
    unauthenticate_user
    redirect_to new_session_url
  end
end

app/controllers/stages_controller.rb
require 'sonic_pi'

class StagesController < ApplicationController

  before_action :find_resource, only: [:show, :reset, :reload, :stop]
  helper_method :resource, :current_contribution

  def index
    @stages = Stage.all
  end

  def show
    pi.run(resource.performance)
  end

  def reload
    respond_to do |format|
      format.js do
        pi.run(resource.performance)
        render status: 200, nothing: true
      end
    end
  end

  def stop
    respond_to do |format|
      format.js do
        pi.stop
        render status: 200, nothing: true
      end
    end
  end

  def reset
    pi.stop
    resource.messages.destroy_all
    resource.contributions.destroy_all
    redirect_to resource
  end

  private

  def find_resource
    @stage = Stage.find(params[:id])
  end

  def current_contribution
    @current_contribution ||= Contribution.find_or_create_by(stage: resource, user: @current_user)
  end

  def resource
    @stage
  end

  def pi
    @pi ||= begin
              proxy = SonicPi.new
              #proxy.test_connection!
              proxy
            end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title euruband
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag    'hightlight/solarized_dark.css', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %meta{:id => @current_user.try(:id), :name => "current-user"}

  %body
    = yield

app/views/messages/_message.html.haml
%article{data:{user:{id:"#{message.user.id}"}}, class: 'message'}
  #user
    .avatar
      = image_tag 'loudly_icon.png'
      #name
        = message.user.name.to_s
      %p
        %small
          = Message::NOTIFICATIONS.sample

app/views/messages/_messages.html.haml
%section{id: "messages", data:{channel: "messages", stage:{id: "#{stage.id}"}}}
  = render stage.messages.take(5)

app/views/messages/_new.html.haml
= form_for [stage, Message.new], remote: true, html: { onsubmit: 'setContent();' } do |form|
  #editor
  = form.text_area :content, value: current_contribution.content
  = form.submit 'Update my contribution', class: 'btn col-4'
  %button.btn.col-4
    Choose from preset

:javascript
  var textarea = jQuery('textarea[id="message_content"]');
  var editor   = ace.edit("editor");

  var setContent = function() {
    textarea.val(editor.getSession().getValue());
  };

  jQuery(document).ready(function(){
    textarea.hide();

    editor.getSession().setValue(textarea.val());
    editor.setTheme("ace/theme/solarized_dark");
    editor.getSession().setMode("ace/mode/ruby");
  });

app/views/messages/create.js.erb
$('#messages').append('<%=j render @message %>');

app/views/stages/index.html.haml
.staging
  .staging-inner
    .staging-copy
      %h1 You're almost ready!

      %p
        Choose a stage to enter.
      %ul
        - @stages.each do |stage|
          %li
            = link_to stage do
              %button
                = stage.title

      = link_to root_url do
        %button
          Wait. Take me back to the root page.

app/views/stages/show.html.haml
.outer-container
  %ul.accordion-tabs-minimal.col-8
    %li.tab-header-and-content
      = link_to 'Your Contrib', '#', class: 'tab-link'
      .tab-content
        = render 'messages/new', stage: resource
    %li.tab-header-and-content
      = link_to 'Complete Performance', '#', class: 'tab-link'
      .tab-content
        %pre
          %code
            = resource.performance.to_s

    %li.tab-header-and-content
      = link_to 'Band mates', class: 'tab-link' do
        Band mates
      .tab-content
        %ul
          - resource.contributions.map(&:user).each do |user|
            %li
              %h4= user.name

  .log.col-4
    = link_to reload_stage_path, remote: true do
      %i{ class: 'material-icons play' }
        play_arrow
    = link_to stop_stage_path, remote: true do
      %i{ class: 'material-icons stop' }
        stop
    = link_to reset_stage_path, method: :put do
      %i{ class: 'material-icons reset' }
        refresh
    = link_to root_path do
      %i{ class: 'material-icons' }
        home
    .messages
      = render 'messages/messages', stage: resource

:javascript
  $(document).ready(function() {
    $('pre code').each(function(i, block) {
      hljs.highlightBlock(block);
    });
  });